<?php

/**
 * Install / uninstall functions for ULearn migrate module.
 */

/**
 * Implements hook_uninstall().
 */
function ulearn_migrate_uninstall() {
  $vars = array(
    'ulearn_migrate_database_name',
    'ulearn_migrate_database_user',
    'ulearn_migrate_database_pass',
    'ulearn_migrate_database_host',
    'ulearn_migrate_database_port',
    'ulearn_migrate_server_url',
  );
  foreach ($vars as $var) {
    variable_del($var);
  }
}
